const RELEASE_PROFILES = {
  early: {
    primaryCategory: "alt-rnb",
    categories: ["alt-rnb", "hip-hop", "late-night"],
    moods: ["confident", "moody", "city"],
    weatherTags: ["cloudy", "night", "windy"],
    settings: ["night", "drive", "city"],
    energy: 3,
  },
  equal: {
    primaryCategory: "alt-rnb",
    categories: ["alt-rnb", "pop", "self-produced"],
    moods: ["sultry", "intense", "moody"],
    weatherTags: ["cloudy", "rainy", "night"],
    settings: ["night", "drive", "alone"],
    energy: 3,
  },
  woops: {
    primaryCategory: "pop-rock",
    categories: ["pop-rock", "bright-pop", "band"],
    moods: ["bright", "playful", "youthful"],
    weatherTags: ["sunny", "windy", "day"],
    settings: ["day", "walk", "drive"],
    energy: 4,
  },
  set: {
    primaryCategory: "r&b",
    categories: ["r&b", "pop", "sleek"],
    moods: ["confident", "smooth", "sensual"],
    weatherTags: ["sunny", "night", "warm"],
    settings: ["night", "drive", "focus"],
    energy: 4,
  },
  ost: {
    primaryCategory: "ballad",
    categories: ["ballad", "ost", "comfort"],
    moods: ["warm", "gentle", "healing"],
    weatherTags: ["cloudy", "cold", "day"],
    settings: ["home", "commute", "evening"],
    energy: 2,
  },
  lovers: {
    primaryCategory: "emotional-pop",
    categories: ["pop", "rock", "r&b"],
    moods: ["yearning", "romantic", "dramatic"],
    weatherTags: ["rainy", "cloudy", "night"],
    settings: ["night", "rain", "alone"],
    energy: 3,
  },
  trauma: {
    primaryCategory: "rock",
    categories: ["rock", "pop-punk", "band"],
    moods: ["rebellious", "cathartic", "restless"],
    weatherTags: ["windy", "sunny", "stormy"],
    settings: ["drive", "workout", "breakup"],
    energy: 4,
  },
  ooli: {
    primaryCategory: "rock",
    categories: ["rock", "acoustic", "alt-rnb"],
    moods: ["introspective", "raw", "homecoming"],
    weatherTags: ["rainy", "cloudy", "windy"],
    settings: ["night", "live", "alone"],
    energy: 3,
  },
  amnesia: {
    primaryCategory: "alt-pop",
    categories: ["alt-pop", "r&b", "winter"],
    moods: ["nostalgic", "cold", "dreamy"],
    weatherTags: ["snowy", "cold", "night"],
    settings: ["winter", "night", "alone"],
    energy: 2,
  },
  lateBallad: {
    primaryCategory: "ballad",
    categories: ["ballad", "rock", "adult-contemporary"],
    moods: ["heartbreak", "grown", "dramatic"],
    weatherTags: ["rainy", "snowy", "night"],
    settings: ["winter", "night", "alone"],
    energy: 2,
  },
  archive: {
    primaryCategory: "alternative",
    categories: ["rock", "alternative", "band"],
    moods: ["cinematic", "restless", "expansive"],
    weatherTags: ["windy", "cloudy", "night"],
    settings: ["night", "drive", "live"],
    energy: 4,
  },
};

const RELEASES = [
  { name: "RECIPE", type: "Digital Single", year: 2016, profile: "early", tracks: ["Recipe"] },
  {
    name: "Baby Ride",
    type: "Digital Single",
    year: 2016,
    profile: "early",
    tracks: ["Baby Ride", "How Have You Been"],
  },
  { name: "POOL", type: "Single", year: 2018, profile: "early", tracks: ["POOL"] },
  { name: "DIFFERENT", type: "Single", year: 2018, profile: "early", tracks: ["DIFFERENT"] },
  { name: "meaningless", type: "Single", year: 2018, profile: "early", tracks: ["meaningless"] },
  {
    name: "EQUAL",
    type: "EP",
    year: 2020,
    profile: "equal",
    tracks: ["LIFT UP", "Accident", "Love Me Harder", "NOID", "Waikiki", "BUCK", "memories"],
  },
  {
    name: "WOOPS!",
    type: "EP",
    year: 2020,
    profile: "woops",
    tracks: ["Trigger", "BUMP BUMP", "On my own", "Thanks to", "Sweater", "Tide"],
  },
  {
    name: "SET",
    type: "Single Album",
    year: 2021,
    profile: "set",
    tracks: ["FEEL LIKE", "Touché", "Rebound"],
  },
  {
    name: "EXchange OST Pt.1",
    type: "OST",
    year: 2021,
    profile: "ost",
    tracks: ["SUN OR SUCK"],
  },
  {
    name: "Monthly Magazine Home OST Pt.5",
    type: "OST",
    year: 2021,
    profile: "ost",
    tracks: ["There For You"],
  },
  { name: "LULLABY", type: "Digital Single", year: 2021, profile: "ost", tracks: ["LULLABY"] },
  {
    name: "ONLY LOVERS LEFT",
    type: "EP",
    year: 2021,
    profile: "lovers",
    tracks: ["Multiply", "Thinkin bout you", "Sour candy", "Kiss of fire", "Chaser", "WAITING"],
  },
  {
    name: "COLORFUL TRAUMA",
    type: "EP",
    year: 2022,
    profile: "trauma",
    tracks: [
      "Dirt on my leather",
      "HIJACK",
      "I hate you",
      "Better and better",
      "Hope to be like you",
    ],
  },
  { name: "Yumi's Cells 2 OST Pt.1", type: "OST", year: 2022, profile: "ost", tracks: ["About You"] },
  { name: "ABYSS", type: "Pre-release Single", year: 2023, profile: "ooli", tracks: ["ABYSS"] },
  {
    name: "OO-LI",
    type: "EP",
    year: 2023,
    profile: "ooli",
    tracks: ["Deep Deep Sleep", "Journey", "Drowning", "Busted", "Who Knows", "Ready to Fight", "ABYSS"],
  },
  {
    name: "AMNESIA",
    type: "Digital Single",
    year: 2023,
    profile: "amnesia",
    tracks: ["AMNESIA", "Behind"],
  },
  {
    name: "I'll Never Love Again",
    type: "Digital Single",
    year: 2025,
    profile: "lateBallad",
    tracks: ["I'll Never Love Again"],
  },
  {
    name: "Falling",
    type: "Digital Single",
    year: 2025,
    profile: "lateBallad",
    tracks: ["Falling"],
  },
  { name: "March", type: "OST", year: 2025, profile: "ost", tracks: ["March"] },
  {
    name: "CINEMA",
    type: "Pre-release Single",
    year: 2026,
    profile: "archive",
    tracks: ["CINEMA", "Bloodline"],
  },
  {
    name: "Archive.1",
    type: "Album",
    year: 2026,
    profile: "archive",
    tracks: [
      "00:30",
      "Super Lazy",
      "하루살이",
      "화근",
      "Human Extinction",
      "비행",
      "Bloodline",
      "Downtown",
      "STOP THAT",
      "NA NA NA",
      "몸부림",
      "BEEP",
      "Plastic",
      "GLASS",
      "CINEMA",
      "사모",
      "To My January",
    ],
  },
];

const SONG_OVERRIDES = {
  Recipe: {
    moods: ["confident", "playful", "swagger"],
    weatherTags: ["sunny", "warm", "day"],
    settings: ["day", "walk", "city"],
    energy: 4,
  },
  "Baby Ride": {
    moods: ["restless", "city", "groovy"],
    weatherTags: ["cloudy", "windy", "night"],
    energy: 3,
  },
  "How Have You Been": {
    primaryCategory: "ballad",
    categories: ["ballad", "r&b", "late-night"],
    moods: ["yearning", "gentle", "nostalgic"],
    weatherTags: ["rainy", "night", "cold"],
    settings: ["alone", "night", "home"],
    energy: 2,
  },
  POOL: {
    primaryCategory: "summer-r&b",
    categories: ["r&b", "summer", "groovy"],
    moods: ["cool", "flirty", "smooth"],
    weatherTags: ["sunny", "hot", "day"],
    settings: ["drive", "vacation", "day"],
    energy: 3,
  },
  DIFFERENT: {
    moods: ["moody", "cool", "precise"],
    weatherTags: ["cloudy", "night", "windy"],
    energy: 3,
  },
  meaningless: {
    primaryCategory: "ballad",
    categories: ["ballad", "alt-rnb", "sad"],
    moods: ["lonely", "tender", "heartbreak"],
    weatherTags: ["rainy", "cold", "night"],
    settings: ["alone", "night", "rain"],
    energy: 1,
  },
  Accident: {
    primaryCategory: "rock-ballad",
    categories: ["rock", "ballad", "dramatic"],
    moods: ["emotional", "intense", "yearning"],
    weatherTags: ["rainy", "night", "stormy"],
    settings: ["alone", "night", "rain"],
    energy: 3,
  },
  "Love Me Harder": {
    moods: ["sultry", "confident", "magnetic"],
    weatherTags: ["night", "warm", "cloudy"],
    settings: ["night", "drive", "focus"],
    energy: 4,
  },
  NOID: {
    moods: ["anxious", "restless", "sharp"],
    weatherTags: ["stormy", "windy", "night"],
    settings: ["night", "city", "focus"],
    energy: 4,
  },
  Waikiki: {
    primaryCategory: "summer-pop",
    categories: ["summer", "pop", "relaxed"],
    moods: ["easygoing", "sunny", "light"],
    weatherTags: ["sunny", "hot", "day"],
    settings: ["vacation", "day", "walk"],
    energy: 3,
  },
  BUCK: {
    primaryCategory: "hip-hop",
    categories: ["hip-hop", "performance", "bass-heavy"],
    moods: ["swagger", "bold", "energetic"],
    weatherTags: ["windy", "night", "stormy"],
    settings: ["workout", "night", "performance"],
    energy: 5,
  },
  memories: {
    primaryCategory: "ballad",
    categories: ["ballad", "memory", "reflective"],
    moods: ["nostalgic", "soft", "wistful"],
    weatherTags: ["rainy", "cloudy", "evening"],
    settings: ["alone", "home", "evening"],
    energy: 2,
  },
  Trigger: {
    moods: ["urgent", "youthful", "bright"],
    weatherTags: ["windy", "sunny", "day"],
    settings: ["drive", "day", "workout"],
    energy: 4,
  },
  "BUMP BUMP": {
    primaryCategory: "bright-pop",
    categories: ["bright-pop", "band", "feel-good"],
    moods: ["playful", "happy", "youthful"],
    weatherTags: ["sunny", "warm", "day"],
    settings: ["day", "walk", "drive"],
    energy: 5,
  },
  "On my own": {
    moods: ["independent", "light", "hopeful"],
    weatherTags: ["sunny", "day", "mild"],
    settings: ["commute", "day", "walk"],
    energy: 3,
  },
  "Thanks to": {
    primaryCategory: "acoustic-pop",
    categories: ["acoustic", "pop", "gratitude"],
    moods: ["warm", "thankful", "gentle"],
    weatherTags: ["sunny", "mild", "day"],
    settings: ["day", "home", "walk"],
    energy: 2,
  },
  Sweater: {
    primaryCategory: "winter-pop",
    categories: ["winter", "pop", "duet"],
    moods: ["cozy", "soft", "sweet"],
    weatherTags: ["snowy", "cold", "night"],
    settings: ["winter", "home", "night"],
    energy: 2,
  },
  Tide: {
    primaryCategory: "ballad",
    categories: ["ballad", "sea-breeze", "slow"],
    moods: ["calm", "reflective", "spacious"],
    weatherTags: ["cloudy", "rainy", "evening"],
    settings: ["evening", "alone", "home"],
    energy: 2,
  },
  "FEEL LIKE": {
    moods: ["slick", "confident", "sensual"],
    weatherTags: ["sunny", "warm", "night"],
    settings: ["night", "drive", "focus"],
    energy: 4,
  },
  "Touché": {
    primaryCategory: "r&b",
    categories: ["r&b", "duet", "city"],
    moods: ["flirty", "sharp", "cool"],
    weatherTags: ["warm", "night", "cloudy"],
    settings: ["night", "city", "drive"],
    energy: 4,
  },
  Rebound: {
    primaryCategory: "pop",
    categories: ["pop", "anthem", "uplifting"],
    moods: ["hopeful", "resilient", "open-road"],
    weatherTags: ["sunny", "windy", "day"],
    settings: ["drive", "day", "workout"],
    energy: 4,
  },
  "SUN OR SUCK": {
    primaryCategory: "ost-pop",
    categories: ["ost", "pop", "breezy"],
    moods: ["bright", "carefree", "easy"],
    weatherTags: ["sunny", "day", "warm"],
    settings: ["commute", "day", "walk"],
    energy: 3,
  },
  "There For You": {
    primaryCategory: "ost-ballad",
    categories: ["ost", "ballad", "comfort"],
    moods: ["comforting", "kind", "steady"],
    weatherTags: ["cloudy", "cold", "evening"],
    settings: ["home", "evening", "commute"],
    energy: 2,
  },
  LULLABY: {
    primaryCategory: "ballad",
    categories: ["ballad", "dream-pop", "comfort"],
    moods: ["sleepy", "cozy", "tender"],
    weatherTags: ["snowy", "cold", "night"],
    settings: ["night", "home", "winter"],
    energy: 1,
  },
  Multiply: {
    moods: ["romantic", "hopeful", "soft"],
    weatherTags: ["cloudy", "sunny", "evening"],
    settings: ["evening", "walk", "day"],
    energy: 2,
  },
  "Thinkin bout you": {
    moods: ["nostalgic", "romantic", "tender"],
    weatherTags: ["cloudy", "evening", "night"],
    settings: ["night", "alone", "home"],
    energy: 2,
  },
  "Sour candy": {
    moods: ["bittersweet", "playful", "twisted"],
    weatherTags: ["cloudy", "warm", "night"],
    settings: ["night", "city", "drive"],
    energy: 3,
  },
  "Kiss of fire": {
    primaryCategory: "dramatic-pop",
    categories: ["dramatic", "latin-pop", "performance"],
    moods: ["passionate", "cinematic", "bold"],
    weatherTags: ["stormy", "night", "windy"],
    settings: ["performance", "night", "focus"],
    energy: 4,
  },
  Chaser: {
    primaryCategory: "rock",
    categories: ["rock", "band", "dramatic"],
    moods: ["urgent", "restless", "cathartic"],
    weatherTags: ["windy", "stormy", "night"],
    settings: ["drive", "night", "workout"],
    energy: 5,
  },
  WAITING: {
    primaryCategory: "ballad-rock",
    categories: ["ballad", "rock", "breakup"],
    moods: ["heartbreak", "emotional", "yearning"],
    weatherTags: ["rainy", "night", "cold"],
    settings: ["rain", "alone", "night"],
    energy: 3,
  },
  "Dirt on my leather": {
    moods: ["rebellious", "rough", "charged"],
    weatherTags: ["windy", "stormy", "day"],
    settings: ["workout", "drive", "day"],
    energy: 5,
  },
  HIJACK: {
    moods: ["urgent", "chaotic", "sharp"],
    weatherTags: ["stormy", "windy", "night"],
    settings: ["workout", "night", "drive"],
    energy: 5,
  },
  "I hate you": {
    primaryCategory: "pop-punk",
    categories: ["pop-punk", "breakup", "anthem"],
    moods: ["cathartic", "bright", "defiant"],
    weatherTags: ["sunny", "windy", "day"],
    settings: ["drive", "breakup", "day"],
    energy: 4,
  },
  "Better and better": {
    primaryCategory: "healing-rock",
    categories: ["rock", "healing", "uplifting"],
    moods: ["resilient", "warm", "optimistic"],
    weatherTags: ["sunny", "mild", "day"],
    settings: ["day", "drive", "walk"],
    energy: 3,
  },
  "Hope to be like you": {
    primaryCategory: "ballad",
    categories: ["ballad", "emotional", "tribute"],
    moods: ["tender", "grateful", "soft"],
    weatherTags: ["rainy", "cloudy", "evening"],
    settings: ["home", "evening", "alone"],
    energy: 2,
  },
  "About You": {
    primaryCategory: "ost-ballad",
    categories: ["ost", "ballad", "romance"],
    moods: ["warm", "longing", "soft"],
    weatherTags: ["cloudy", "rainy", "evening"],
    settings: ["commute", "evening", "home"],
    energy: 2,
  },
  ABYSS: {
    primaryCategory: "alt-rnb",
    categories: ["alt-rnb", "dark", "immersive"],
    moods: ["lonely", "deep", "atmospheric"],
    weatherTags: ["rainy", "cloudy", "night"],
    settings: ["night", "alone", "headphones"],
    energy: 2,
  },
  "Deep Deep Sleep": {
    primaryCategory: "dream-pop",
    categories: ["dream-pop", "soft-rock", "sleepy"],
    moods: ["dreamy", "gentle", "weightless"],
    weatherTags: ["cloudy", "night", "cold"],
    settings: ["night", "home", "rest"],
    energy: 2,
  },
  Journey: {
    primaryCategory: "acoustic-rock",
    categories: ["acoustic", "rock", "hopeful"],
    moods: ["hopeful", "warm", "open-road"],
    weatherTags: ["sunny", "windy", "day"],
    settings: ["drive", "travel", "day"],
    energy: 3,
  },
  Drowning: {
    primaryCategory: "rock-ballad",
    categories: ["rock", "ballad", "vocal"],
    moods: ["explosive", "emotional", "intense"],
    weatherTags: ["rainy", "stormy", "night"],
    settings: ["live", "night", "catharsis"],
    energy: 5,
  },
  Busted: {
    primaryCategory: "garage-rock",
    categories: ["rock", "garage", "fast"],
    moods: ["messy", "energetic", "wild"],
    weatherTags: ["windy", "stormy", "day"],
    settings: ["drive", "workout", "day"],
    energy: 5,
  },
  "Who Knows": {
    primaryCategory: "indie-pop",
    categories: ["indie-pop", "light", "curious"],
    moods: ["curious", "bright", "wandering"],
    weatherTags: ["sunny", "mild", "day"],
    settings: ["walk", "day", "commute"],
    energy: 3,
  },
  "Ready to Fight": {
    primaryCategory: "punk-rock",
    categories: ["punk-rock", "performance", "adrenaline"],
    moods: ["charged", "fearless", "aggressive"],
    weatherTags: ["stormy", "windy", "night"],
    settings: ["workout", "night", "performance"],
    energy: 5,
  },
  AMNESIA: {
    primaryCategory: "winter-alt-pop",
    categories: ["winter", "alt-pop", "memory"],
    moods: ["nostalgic", "cold", "ache"],
    weatherTags: ["snowy", "cold", "night"],
    settings: ["winter", "alone", "night"],
    energy: 2,
  },
  Behind: {
    primaryCategory: "winter-ballad",
    categories: ["ballad", "winter", "soft"],
    moods: ["quiet", "regret", "tender"],
    weatherTags: ["snowy", "cold", "evening"],
    settings: ["winter", "home", "evening"],
    energy: 1,
  },
  "I'll Never Love Again": {
    primaryCategory: "ballad",
    categories: ["ballad", "heartbreak", "adult-contemporary"],
    moods: ["heartbreak", "devastated", "dramatic"],
    weatherTags: ["snowy", "rainy", "night"],
    settings: ["winter", "alone", "night"],
    energy: 2,
  },
  Falling: {
    primaryCategory: "rock-ballad",
    categories: ["rock", "duet", "heartbreak"],
    moods: ["aching", "soaring", "open-heart"],
    weatherTags: ["rainy", "windy", "night"],
    settings: ["night", "drive", "alone"],
    energy: 3,
  },
  March: {
    primaryCategory: "ost-ballad",
    categories: ["ost", "ballad", "seasonal"],
    moods: ["gentle", "hopeful", "spring"],
    weatherTags: ["mild", "cloudy", "day"],
    settings: ["day", "commute", "walk"],
    energy: 2,
  },
  CINEMA: {
    primaryCategory: "cinematic-rock",
    categories: ["rock", "cinematic", "anthem"],
    moods: ["nostalgic", "sweeping", "uplifting"],
    weatherTags: ["cloudy", "night", "windy"],
    settings: ["night", "drive", "movie-ending"],
    energy: 4,
  },
  Bloodline: {
    primaryCategory: "alternative",
    categories: ["alternative", "dark", "performance"],
    moods: ["tense", "brooding", "sharp"],
    weatherTags: ["stormy", "cloudy", "night"],
    settings: ["night", "performance", "focus"],
    energy: 4,
  },
  "00:30": {
    primaryCategory: "late-night",
    categories: ["late-night", "alternative", "intro"],
    moods: ["restless", "city", "insomniac"],
    weatherTags: ["night", "cloudy", "windy"],
    settings: ["night", "headphones", "city"],
    energy: 3,
  },
  "Super Lazy": {
    primaryCategory: "indie-pop",
    categories: ["indie-pop", "quirky", "laid-back"],
    moods: ["lazy", "dry-humor", "light"],
    weatherTags: ["sunny", "mild", "day"],
    settings: ["weekend", "home", "day"],
    energy: 2,
  },
  하루살이: {
    primaryCategory: "ballad",
    categories: ["ballad", "fleeting", "lyrical"],
    moods: ["fragile", "short-lived", "soft"],
    weatherTags: ["rainy", "cloudy", "night"],
    settings: ["night", "alone", "home"],
    energy: 2,
  },
  화근: {
    primaryCategory: "rock",
    categories: ["rock", "dark", "friction"],
    moods: ["sharp", "heated", "restless"],
    weatherTags: ["stormy", "windy", "night"],
    settings: ["drive", "night", "workout"],
    energy: 4,
  },
  "Human Extinction": {
    primaryCategory: "rock",
    categories: ["rock", "philosophical", "anthem"],
    moods: ["grand", "urgent", "cinematic"],
    weatherTags: ["stormy", "windy", "night"],
    settings: ["live", "night", "drive"],
    energy: 5,
  },
  비행: {
    primaryCategory: "alternative-pop",
    categories: ["alternative", "flight", "release"],
    moods: ["airy", "escaping", "hopeful"],
    weatherTags: ["sunny", "windy", "day"],
    settings: ["travel", "day", "drive"],
    energy: 3,
  },
  Downtown: {
    primaryCategory: "city-pop",
    categories: ["city-pop", "night", "groove"],
    moods: ["urban", "cool", "gliding"],
    weatherTags: ["night", "mild", "cloudy"],
    settings: ["night", "city", "drive"],
    energy: 3,
  },
  "STOP THAT": {
    primaryCategory: "funk-rock",
    categories: ["funk-rock", "playful", "band"],
    moods: ["cheeky", "fast", "bold"],
    weatherTags: ["sunny", "windy", "day"],
    settings: ["day", "drive", "workout"],
    energy: 4,
  },
  "NA NA NA": {
    primaryCategory: "pop-rock",
    categories: ["pop-rock", "love-song", "singalong"],
    moods: ["bright", "hooky", "romantic"],
    weatherTags: ["sunny", "warm", "day"],
    settings: ["drive", "day", "walk"],
    energy: 4,
  },
  몸부림: {
    primaryCategory: "rock-ballad",
    categories: ["rock", "struggle", "dramatic"],
    moods: ["desperate", "raw", "cathartic"],
    weatherTags: ["stormy", "rainy", "night"],
    settings: ["night", "alone", "catharsis"],
    energy: 4,
  },
  BEEP: {
    primaryCategory: "alt-pop",
    categories: ["alt-pop", "quirky", "electro"],
    moods: ["nervy", "playful", "odd"],
    weatherTags: ["cloudy", "day", "mild"],
    settings: ["day", "city", "focus"],
    energy: 3,
  },
  Plastic: {
    primaryCategory: "alternative",
    categories: ["alternative", "dark-pop", "synthetic"],
    moods: ["cold", "detached", "sharp"],
    weatherTags: ["cloudy", "night", "cold"],
    settings: ["night", "city", "focus"],
    energy: 3,
  },
  GLASS: {
    primaryCategory: "ballad",
    categories: ["ballad", "fragile", "clear"],
    moods: ["delicate", "transparent", "quiet"],
    weatherTags: ["snowy", "cold", "night"],
    settings: ["night", "home", "winter"],
    energy: 2,
  },
  사모: {
    primaryCategory: "ballad",
    categories: ["ballad", "traditional-touch", "devotion"],
    moods: ["earnest", "deep", "devoted"],
    weatherTags: ["rainy", "cold", "night"],
    settings: ["night", "alone", "home"],
    energy: 2,
  },
  "To My January": {
    primaryCategory: "winter-ballad",
    categories: ["ballad", "winter", "letter-song"],
    moods: ["nostalgic", "warm", "farewell"],
    weatherTags: ["snowy", "cold", "evening"],
    settings: ["winter", "home", "evening"],
    energy: 2,
  },
};

function uniqueValues(...collections) {
  return [...new Set(collections.flat().filter(Boolean))];
}

function buildCatalog() {
  const catalogMap = new Map();

  RELEASES.forEach((release) => {
    const profile = RELEASE_PROFILES[release.profile];

    release.tracks.forEach((title) => {
      const override = SONG_OVERRIDES[title] || {};
      const key = title.toLowerCase();
      const existing = catalogMap.get(key);

      const entry = {
        id: key.replaceAll(" ", "-"),
        title,
        year: release.year,
        primaryRelease: existing ? existing.primaryRelease : release.name,
        releaseType: existing ? existing.releaseType : release.type,
        releaseHistory: uniqueValues(existing?.releaseHistory || [], release.name),
        primaryCategory: override.primaryCategory || profile.primaryCategory,
        categories: uniqueValues(profile.categories, override.categories || []),
        moods: uniqueValues(profile.moods, override.moods || []),
        weatherTags: uniqueValues(profile.weatherTags, override.weatherTags || []),
        settings: uniqueValues(profile.settings, override.settings || []),
        energy: override.energy || profile.energy,
      };

      catalogMap.set(key, entry);
    });
  });

  return [...catalogMap.values()].sort((left, right) => {
    if (left.year !== right.year) {
      return left.year - right.year;
    }
    return left.title.localeCompare(right.title);
  });
}

export const SONG_CATALOG = buildCatalog();
export const CATEGORY_OPTIONS = [
  "all",
  ...new Set(SONG_CATALOG.map((song) => song.primaryCategory)),
];
export const MOOD_OPTIONS = [
  "all",
  ...new Set(SONG_CATALOG.flatMap((song) => song.moods)),
];
