from __future__ import annotations

from .models import SongRecord


LOCAL_SONG_CATALOG: tuple[SongRecord, ...] = (
    SongRecord(
        id="waiting",
        title="Waiting",
        album="Only Lovers Left",
        release_year=2021,
        lyrics_summary="A late-night breakup song about waiting for someone who may never come back.",
        mood_tags=["melancholic", "emotional", "yearning"],
        weather_tags=["rainy", "cloudy", "night"],
        time_tags=["night", "evening"],
        emotion_tags=["sad", "lonely", "nostalgic"],
        lyrics_themes=["waiting", "longing", "loneliness"],
        energy_score=0.62,
        sentiment_score=-0.71,
    ),
    SongRecord(
        id="different",
        title="Different",
        album="Different",
        release_year=2018,
        lyrics_summary="A restrained song about emotional distance, identity, and the feeling of not aligning with someone anymore.",
        mood_tags=["cool", "moody", "precise"],
        weather_tags=["cloudy", "night", "windy"],
        time_tags=["night"],
        emotion_tags=["lonely", "nostalgic"],
        lyrics_themes=["identity", "distance", "difference"],
        energy_score=0.56,
        sentiment_score=-0.42,
    ),
    SongRecord(
        id="accident",
        title="Accident",
        album="Equal",
        release_year=2020,
        lyrics_summary="A dramatic confession track about spiraling emotions, regret, and emotional collision.",
        mood_tags=["emotional", "intense", "yearning"],
        weather_tags=["rainy", "night", "stormy"],
        time_tags=["night"],
        emotion_tags=["sad", "lonely"],
        lyrics_themes=["regret", "turmoil", "self-reflection"],
        energy_score=0.64,
        sentiment_score=-0.66,
    ),
    SongRecord(
        id="meaningless",
        title="meaningless",
        album="meaningless",
        release_year=2018,
        lyrics_summary="A sparse and aching song that lingers on emptiness after a relationship loses meaning.",
        mood_tags=["lonely", "tender", "heartbreak"],
        weather_tags=["rainy", "cold", "night"],
        time_tags=["night"],
        emotion_tags=["sad", "lonely"],
        lyrics_themes=["emptiness", "distance", "loneliness"],
        energy_score=0.28,
        sentiment_score=-0.82,
    ),
    SongRecord(
        id="love-me-harder",
        title="Love Me Harder",
        album="Equal",
        release_year=2020,
        lyrics_summary="A confident and magnetic track about desire, attraction, and wanting stronger emotional intensity.",
        mood_tags=["sultry", "confident", "magnetic"],
        weather_tags=["night", "warm", "cloudy"],
        time_tags=["night", "evening"],
        emotion_tags=["excited"],
        lyrics_themes=["desire", "confidence", "attraction"],
        energy_score=0.8,
        sentiment_score=0.21,
    ),
    SongRecord(
        id="journey",
        title="Journey",
        album="OO-LI",
        release_year=2023,
        lyrics_summary="A comforting travel-like song about moving forward, staying hopeful, and finding peace on the way.",
        mood_tags=["warm", "hopeful", "calm"],
        weather_tags=["sunny", "windy", "day"],
        time_tags=["day", "morning"],
        emotion_tags=["calm", "nostalgic"],
        lyrics_themes=["movement", "hope", "healing"],
        energy_score=0.48,
        sentiment_score=0.62,
    ),
    SongRecord(
        id="drowning",
        title="Drowning",
        album="OO-LI",
        release_year=2023,
        lyrics_summary="An explosive vocal track that captures being overwhelmed by emotion until it breaks into catharsis.",
        mood_tags=["explosive", "emotional", "intense"],
        weather_tags=["rainy", "stormy", "night"],
        time_tags=["night"],
        emotion_tags=["sad", "excited"],
        lyrics_themes=["overwhelm", "emotion", "collapse"],
        energy_score=0.96,
        sentiment_score=-0.5,
    ),
    SongRecord(
        id="abyss",
        title="ABYSS",
        album="OO-LI",
        release_year=2023,
        lyrics_summary="A dark and immersive song about sinking inward and confronting loneliness in silence.",
        mood_tags=["lonely", "deep", "atmospheric"],
        weather_tags=["rainy", "cloudy", "night"],
        time_tags=["night"],
        emotion_tags=["lonely", "nostalgic"],
        lyrics_themes=["depth", "loneliness", "introspection"],
        energy_score=0.34,
        sentiment_score=-0.74,
    ),
    SongRecord(
        id="i-hate-you",
        title="I hate you",
        album="Colorful Trauma",
        release_year=2022,
        lyrics_summary="A cathartic breakup anthem that transforms frustration into release and forward motion.",
        mood_tags=["cathartic", "bright", "defiant"],
        weather_tags=["sunny", "windy", "day"],
        time_tags=["day", "evening"],
        emotion_tags=["excited", "sad"],
        lyrics_themes=["breakup", "defiance", "release"],
        energy_score=0.84,
        sentiment_score=0.18,
    ),
    SongRecord(
        id="chaser",
        title="Chaser",
        album="Only Lovers Left",
        release_year=2021,
        lyrics_summary="A restless rock-leaning song about pursuit, obsession, and emotional urgency.",
        mood_tags=["urgent", "restless", "cathartic"],
        weather_tags=["windy", "stormy", "night"],
        time_tags=["night"],
        emotion_tags=["excited", "lonely"],
        lyrics_themes=["pursuit", "obsession", "restlessness"],
        energy_score=0.88,
        sentiment_score=-0.34,
    ),
)
