from __future__ import annotations

from .models import SongRecord


LOCAL_SONG_CATALOG: tuple[SongRecord, ...] = (
    SongRecord(
        id="waiting",
        title="Waiting",
        album="Only Lovers Left",
        release_year=2021,
        lyrics_summary="돌아오지 않을지도 모르는 사람을 기다리는 마음을 늦은 밤의 이별 감성으로 풀어낸 곡이다.",
        mood_tags=["melancholic", "emotional", "yearning"],
        weather_tags=["rainy", "cloudy", "night"],
        time_tags=["night", "evening"],
        emotion_tags=["sad", "lonely", "nostalgic"],
        lyrics_themes=["waiting", "longing", "loneliness"],
        energy_score=0.62,
        sentiment_score=-0.71,
    ),
    SongRecord(
        id="different",
        title="Different",
        album="Different",
        release_year=2018,
        lyrics_summary="감정적 거리감과 어긋남, 그리고 서로 달라졌다는 감각을 차분하게 풀어내는 곡이다.",
        mood_tags=["cool", "moody", "precise"],
        weather_tags=["cloudy", "night", "windy"],
        time_tags=["night"],
        emotion_tags=["lonely", "nostalgic"],
        lyrics_themes=["identity", "distance", "difference"],
        energy_score=0.56,
        sentiment_score=-0.42,
    ),
    SongRecord(
        id="accident",
        title="Accident",
        album="Equal",
        release_year=2020,
        lyrics_summary="휘몰아치는 감정과 후회, 관계의 충돌을 드라마틱하게 고백하는 곡이다.",
        mood_tags=["emotional", "intense", "yearning"],
        weather_tags=["rainy", "night", "stormy"],
        time_tags=["night"],
        emotion_tags=["sad", "lonely"],
        lyrics_themes=["regret", "turmoil", "self-reflection"],
        energy_score=0.64,
        sentiment_score=-0.66,
    ),
    SongRecord(
        id="meaningless",
        title="meaningless",
        album="meaningless",
        release_year=2018,
        lyrics_summary="관계가 의미를 잃은 뒤 남겨진 공허함과 아픔을 담담하게 붙드는 곡이다.",
        mood_tags=["lonely", "tender", "heartbreak"],
        weather_tags=["rainy", "cold", "night"],
        time_tags=["night"],
        emotion_tags=["sad", "lonely"],
        lyrics_themes=["emptiness", "distance", "loneliness"],
        energy_score=0.28,
        sentiment_score=-0.82,
    ),
    SongRecord(
        id="love-me-harder",
        title="Love Me Harder",
        album="Equal",
        release_year=2020,
        lyrics_summary="욕망과 끌림, 더 강한 감정의 밀도를 원한다는 마음을 자신감 있게 표현한 곡이다.",
        mood_tags=["sultry", "confident", "magnetic"],
        weather_tags=["night", "warm", "cloudy"],
        time_tags=["night", "evening"],
        emotion_tags=["excited"],
        lyrics_themes=["desire", "confidence", "attraction"],
        energy_score=0.8,
        sentiment_score=0.21,
    ),
    SongRecord(
        id="journey",
        title="Journey",
        album="OO-LI",
        release_year=2023,
        lyrics_summary="앞으로 나아가며 희망을 놓지 않고, 그 과정 속에서 평온을 찾아가는 마음을 담은 곡이다.",
        mood_tags=["warm", "hopeful", "calm"],
        weather_tags=["sunny", "windy", "day"],
        time_tags=["day", "morning"],
        emotion_tags=["calm", "nostalgic"],
        lyrics_themes=["movement", "hope", "healing"],
        energy_score=0.48,
        sentiment_score=0.62,
    ),
    SongRecord(
        id="drowning",
        title="Drowning",
        album="OO-LI",
        release_year=2023,
        lyrics_summary="감정에 잠식되듯 휩쓸리다가 결국 폭발적인 해소로 이어지는 순간을 담은 곡이다.",
        mood_tags=["explosive", "emotional", "intense"],
        weather_tags=["rainy", "stormy", "night"],
        time_tags=["night"],
        emotion_tags=["sad", "excited"],
        lyrics_themes=["overwhelm", "emotion", "collapse"],
        energy_score=0.96,
        sentiment_score=-0.5,
    ),
    SongRecord(
        id="abyss",
        title="ABYSS",
        album="OO-LI",
        release_year=2023,
        lyrics_summary="고요한 외로움 속으로 가라앉으며 내면의 깊은 감정을 마주하게 만드는 곡이다.",
        mood_tags=["lonely", "deep", "atmospheric"],
        weather_tags=["rainy", "cloudy", "night"],
        time_tags=["night"],
        emotion_tags=["lonely", "nostalgic"],
        lyrics_themes=["depth", "loneliness", "introspection"],
        energy_score=0.34,
        sentiment_score=-0.74,
    ),
    SongRecord(
        id="i-hate-you",
        title="I hate you",
        album="Colorful Trauma",
        release_year=2022,
        lyrics_summary="이별에서 비롯된 분노와 답답함을 해방감과 전진의 에너지로 바꾸는 곡이다.",
        mood_tags=["cathartic", "bright", "defiant"],
        weather_tags=["sunny", "windy", "day"],
        time_tags=["day", "evening"],
        emotion_tags=["excited", "sad"],
        lyrics_themes=["breakup", "defiance", "release"],
        energy_score=0.84,
        sentiment_score=0.18,
    ),
    SongRecord(
        id="chaser",
        title="Chaser",
        album="Only Lovers Left",
        release_year=2021,
        lyrics_summary="쫓고 집착하고 조급해지는 감정을 거친 록 사운드로 밀어붙이는 곡이다.",
        mood_tags=["urgent", "restless", "cathartic"],
        weather_tags=["windy", "stormy", "night"],
        time_tags=["night"],
        emotion_tags=["excited", "lonely"],
        lyrics_themes=["pursuit", "obsession", "restlessness"],
        energy_score=0.88,
        sentiment_score=-0.34,
    ),
)
